# Generated by Django 4.0.2 on 2022-09-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_image',
        ),
    ]
